[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]

# Database
diesel = { version = "2.1.0", features = ["sqlite", "r2d2"] }
serde = { version = "1.0.175", features = ["derive"] }

# Other
anyhow = "1.0.72"
thiserror = "1.0.48"
once_cell = "1.18.0"
